package nl.taico.tekkitrestrict.config;

import java.util.ArrayList;

public class EEPatchConfig extends TRConfig {
	public static ArrayList<String> defaultContents(boolean extra){
		final ArrayList<String> tbr = new ArrayList<String>(700);
		
		tbr.add("############################################################################################");
		tbr.add("## Configuration file for TekkitRestrict                                                  ##");
		tbr.add("## Authors: Taeir, DreadEnd (aka DreadSlicer)                                             ##");
		tbr.add("## BukkitDev: http://dev.bukkit.org/server-mods/tekkit-restrict/                          ##");
		tbr.add("## Please ask questions/report issues on the BukkitDev page.                              ##");
		tbr.add("############################################################################################");
		tbr.add("");
		tbr.add("############################################################################################");
		tbr.add("#################################### EEPatch Functions #####################################");
		tbr.add("############################################################################################");
		tbr.add("# Set the maximum charge for a tool. (CaPSloCk Safe)");
		tbr.add("#");
		tbr.add("# Q: Why should I use this one over the one in ModModifications.config?");
		tbr.add("# A: Because this one directly blocks a player from charging. The one in the other config");
		tbr.add("#    uncharges a tool a level as soon as it finds one in someone's inventory that is");
		tbr.add("#    charged too high. Using this one over the one in ModModifications.config results in");
		tbr.add("#    a faster response and less server load.");
		tbr.add("#");
		tbr.add("# Default Charge Levels:");
		tbr.add("# 3 Charge Levels: DM tools");
		tbr.add("# 4 Charge Levels: RM tools, Destruction Catalyst, Hyperkinetic Lens, ");
		tbr.add("# 5 Charge Levels: Katar, Morning Star, Zero Ring, Ring of Ignition, Evertide Amulet");
		tbr.add("#                  Vulcanite Amulet, Philosopher's Stone, Watch of Flowing Time,");
		tbr.add("#                  Mercurial Eye");
		tbr.add("# 8 Charge Levels: Catalytic Lens");
		tbr.add("#");
		tbr.add("# NOTE: Charge Levels start at level 0. This means that:");
		tbr.add("# DM tools have Charge Levels 0, 1 and 2");
		tbr.add("# RM tools have Charge Levels 0, 1, 2 and 3");
		tbr.add("# Etc.");
		tbr.add("#");
		tbr.add("# Example:");
		tbr.add("# MaxCharge:");
		tbr.add("# - \"RMPickaxe 1\"   - Makes Red Matter Pickaxes charge to level 1 at max.");
		tbr.add("# - \"RMTools 2\"     - Makes all Red Matter Tools charge to level 2 at max. (This");
		tbr.add("#                     does NOT include Katar and Morning Star)");
		tbr.add("# - \"ZeroRing 3\"    - Makes the Zero Ring charge to level 3 at max.");
		tbr.add("# - \"Rings 2\"       - Makes the Zero Ring and the Ring of Ignition charge to level 2 max.");
		tbr.add("");
		tbr.add("EEMaxCharge: []");
		if (extra) tbr.add("#:-;-:# EEMaxCharge");
		tbr.add("");
		tbr.add("############################################################################################");
		tbr.add("###################################### Disable Actions #####################################");
		tbr.add("############################################################################################");
		tbr.add("# Here you can define what tool/ring/amulet actions you want to disable.");
		tbr.add("# Every value can either be true (allowed) or false (NOT allowed).");
		tbr.add("#");
		tbr.add("# Long version: ");
		tbr.add("# Keep in mind that with EEPatch, every action that changes a block checks if the player");
		tbr.add("# that does the action has permission in that location. This means that areas protected by");
		tbr.add("# GriefPrevention, WorldGuard, PreciousStones, Towns, Factions, LWC or any other protection");
		tbr.add("# plugin cannot be modified by these actions if the player does not have permission to break");
		tbr.add("# blocks at the location.");
		tbr.add("# For this reason, most actions that break blocks in a radius don't have to be blocked as");
		tbr.add("# they will already be blocked in protected areas. Only if you want to prevent ");
		tbr.add("# \"nature grief\" or just want to make the game harder you should disable these actions.");
		tbr.add("#");
		tbr.add("# Short version:");
		tbr.add("# EEPatch itself will make griefing with EE Tools impossible where it is not wanted, so you");
		tbr.add("# don't have to block most actions that break blocks in a radius, unless you don't want");
		tbr.add("# people to ever use these actions, not even where they are wanted.");
		tbr.add("#");
		tbr.add("# NOTE: If you change someone's permissions, it can take up to 60 seconds before the changes");
		tbr.add("# take effect.");
		tbr.add("#");
		tbr.add("# Default: true for all values");
		tbr.add("Actions:");
		tbr.add("    Tools:");
		tbr.add("        DarkMatter:");
		tbr.add("            Pickaxe:");
		tbr.add("                # Break-3 is an ability that DM and RM Pickaxes and Shovels, and the Red");
		tbr.add("                # Morning Star has.");
		tbr.add("                #");
		tbr.add("                # It allows you to break 3 blocks at a time (instead of the default 1).");
		tbr.add("                # The pattern it breaks these blocks in is dependent on the mode");
		tbr.add("                # (Tall, Wide or Long)");
		tbr.add("                Break-3:");
		tbr.add("                    Tall: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.DarkMatter.Pickaxe.Break-3.Tall");
		tbr.add("                    Wide: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.DarkMatter.Pickaxe.Break-3.Wide");
		tbr.add("                    Long: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.DarkMatter.Pickaxe.Break-3.Long");
		tbr.add("");
		tbr.add("                # BreakOreVein: If you rightclick on an ore block with a DM Pickaxe, it");
		tbr.add("                # will break all ores of the same kind surrounding the ore block you");
		tbr.add("                # clicked.");
		tbr.add("                BreakOreVein: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.DarkMatter.Pickaxe.BreakOreVein");
		tbr.add("            Axe:");
		tbr.add("                # BreakRadius: If you press R while holding an DM Axe, or if you rightclick");
		tbr.add("                # with one, it will break axe-type blocks in a radius that is dependent on");
		tbr.add("                # the charge level of the tool.");
		tbr.add("                #");
		tbr.add("                # Axe-type blocks = blocks that are supposed to be mined with an axe.");
		tbr.add("                # (Logs, wood and most blocks made out of wood)");
		tbr.add("                BreakRadius: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.DarkMatter.Axe.BreakRadius");
		tbr.add("            Shovel:");
		tbr.add("                # Break-3: See DM Pickaxe");
		tbr.add("                Break-3:");
		tbr.add("                    Tall: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.DarkMatter.Shovel.Break-3.Tall");
		tbr.add("                    Wide: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.DarkMatter.Shovel.Break-3.Wide");
		tbr.add("                    Long: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.DarkMatter.Shovel.Break-3.Long");
		tbr.add("");
		tbr.add("                # BreakRadius: If you press R while holding a DM Shovel, or if you");
		tbr.add("                # rightclick with one, it will break shovel-type blocks in a radius that");
		tbr.add("                # is dependent on the charge level of the tool.");
		tbr.add("                #");
		tbr.add("                # Shovel-type blocks = blocks that are supposed to be mined with a shovel.");
		tbr.add("                # (Dirt, grass, gravel, sand, etc.)");
		tbr.add("                BreakRadius: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.DarkMatter.Shovel.BreakRadius");
		tbr.add("            Hoe:");
		tbr.add("                # TillRadius: If you press R while holding a DM Hoe, or if you rightclick");
		tbr.add("                # with one, it will till all grass and dirt in a radius that is dependent");
		tbr.add("                # on the charge level of the tool.");
		tbr.add("                #");
		tbr.add("                # Tip of Taeir: Disable this to prevent major \"nature grief\".");
		tbr.add("                TillRadius: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.DarkMatter.Hoe.TillRadius");
		tbr.add("            Shears:");
		tbr.add("                # BreakRadius: If you press R while holding DM Shears, or if you");
		tbr.add("                # rightclick with some, it will break shear-type blocks in a radius that");
		tbr.add("                # is dependent on the charge level of the tool.");
		tbr.add("                #");
		tbr.add("                # Shear-type blocks = blocks that are supposed to be broken with shears.");
		tbr.add("                # (Wool, leaves, tall grass, vines, etc.)");
		tbr.add("                BreakRadius: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.DarkMatter.Shears.BreakRadius");
		tbr.add("");
		tbr.add("                # Shear: If you rightclick a shearable mob (sheep, mooshroom) with DM");
		tbr.add("                # Shears, you will shear it.");
		tbr.add("                Shear: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.DarkMatter.Shears.Shear");
		tbr.add("            Hammer:");
		tbr.add("                # MegaBreak: If you enable Mega Hammer mode, and you rightclick with a");
		tbr.add("                # DM Hammer, it will break a very large cube of blocks around where you");
		tbr.add("                # clicked.");
		tbr.add("                MegaBreak: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.DarkMatter.Hammer.MegaBreak");
		tbr.add("");
		tbr.add("                # BreakRadius: If you press R while holding a DM Hammer, or if you");
		tbr.add("                # rightclick with one, it will break stone-type blocks in a square whose");
		tbr.add("                # size is dependent on the charge level of the tool.");
		tbr.add("                #");
		tbr.add("                # (Hammer-type blocks = stone, cobblestone, ores, netherrack, ice, etc.)");
		tbr.add("                BreakRadius: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.DarkMatter.Hammer.BreakRadius");
		tbr.add("            Sword:");
		tbr.add("                # AttackRadius: If you press R with a DM Sword, you will attack mobs in a");
		tbr.add("                # range around you which is dependent on the charge level of the tool.");
		tbr.add("                # You can change the mode of the sword to switch between only damaging");
		tbr.add("                # hostile mobs (excluding players) and all mobs (including players).");
		tbr.add("                AttackRadius: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.DarkMatter.Sword.AttackRadius");
		tbr.add("        RedMatter:");
		tbr.add("            Pickaxe:");
		tbr.add("                # Break-3: See DM Pickaxe");
		tbr.add("                Break-3:");
		tbr.add("                    Tall: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.RedMatter.Pickaxe.Break-3.Tall");
		tbr.add("                    Wide: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.RedMatter.Pickaxe.Break-3.Wide");
		tbr.add("                    Long: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.RedMatter.Pickaxe.Break-3.Long");
		tbr.add("");
		tbr.add("                # BreakOreVein: If you rightclick on an ore block with a RM Pickaxe, it");
		tbr.add("                # will break all ores of the same kind surrounding the ore block you");
		tbr.add("                # clicked.");
		tbr.add("                BreakOreVein: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.RedMatter.Pickaxe.BreakOreVein");
		tbr.add("            Axe:");
		tbr.add("                # BreakRadius: If you press R while holding an RM Axe, or if you rightclick");
		tbr.add("                # with one, it will break axe-type blocks in a radius that is dependent on");
		tbr.add("                # the charge level of the tool.");
		tbr.add("                #");
		tbr.add("                # Axe-type blocks = blocks that are supposed to be mined with an axe.");
		tbr.add("                # (Logs, wood and most blocks made out of wood)");
		tbr.add("                BreakRadius: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.RedMatter.Axe.BreakRadius");
		tbr.add("            Shovel:");
		tbr.add("                # Break-3: See DM Pickaxe");
		tbr.add("                Break-3:");
		tbr.add("                    Tall: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.RedMatter.Shovel.Break-3.Tall");
		tbr.add("                    Wide: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.RedMatter.Shovel.Break-3.Wide");
		tbr.add("                    Long: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.RedMatter.Shovel.Break-3.Long");
		tbr.add("");
		tbr.add("                # BreakRadius: If you press R while holding a RM Shovel, or if you");
		tbr.add("                # rightclick with one, it will break shovel-type blocks in a radius that");
		tbr.add("                # is dependent on the charge level of the tool.");
		tbr.add("                #");
		tbr.add("                # Shovel-type blocks = blocks that are supposed to be mined with a shovel.");
		tbr.add("                # (Dirt, grass, gravel, sand, etc.)");
		tbr.add("                BreakRadius: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.RedMatter.Shovel.BreakRadius");
		tbr.add("            Hoe:");
		tbr.add("                # TillRadius: If you press R while holding a RM Hoe, or if you rightclick");
		tbr.add("                # with one, it will till all grass and dirt in a radius that is dependent");
		tbr.add("                # on the charge level of the tool.");
		tbr.add("                #");
		tbr.add("                # Tip of Taeir: Disable this to prevent major \"nature grief\".");
		tbr.add("                TillRadius: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.RedMatter.Hoe.TillRadius");
		tbr.add("            Shears:");
		tbr.add("                # BreakRadius: If you press R while holding RM Shears, or if you");
		tbr.add("                # rightclick with some, it will break shear-type blocks in a radius that");
		tbr.add("                # is dependent on the charge level of the tool.");
		tbr.add("                #");
		tbr.add("                # Shear-type blocks = blocks that are supposed to be broken with shears.");
		tbr.add("                # (Wool, leaves, tall grass, vines, etc.)");
		tbr.add("                BreakRadius: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.RedMatter.Shears.BreakRadius");
		tbr.add("");
		tbr.add("                # Shear: If you rightclick a shearable mob (sheep, mooshroom) with RM");
		tbr.add("                # Shears, you will shear it.");
		tbr.add("                Shear: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.RedMatter.Shears.Shear");
		tbr.add("            Hammer:");
		tbr.add("                # MegaBreak: If you enable Mega Hammer mode, and you rightclick with a");
		tbr.add("                # RM Hammer, it will break a very large cube of blocks around where you");
		tbr.add("                # clicked.");
		tbr.add("                MegaBreak: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.RedMatter.Hammer.MegaBreak");
		tbr.add("");
		tbr.add("                # BreakRadius: If you press R while holding a RM Hammer, or if you");
		tbr.add("                # rightclick with one, it will break stone-type blocks in a square whose");
		tbr.add("                # size is dependent on the charge level of the tool.");
		tbr.add("                #");
		tbr.add("                # (Hammer-type blocks = stone, cobblestone, ores, netherrack, ice, etc.)");
		tbr.add("                BreakRadius: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.RedMatter.Hammer.BreakRadius");
		tbr.add("            Sword:");
		tbr.add("                # AttackRadius: If you press R with a RM Sword, you will attack mobs in a");
		tbr.add("                # range around you which is dependent on the charge level of the tool.");
		tbr.add("                # You can change the mode of the sword to switch between only damaging");
		tbr.add("                # hostile mobs (excluding players) and all mobs (including players).");
		tbr.add("                AttackRadius: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.RedMatter.Sword.AttackRadius");
		tbr.add("        Katar:");
		tbr.add("            # BreakRadius: If you rightclick with a Katar on wood-type blocks, it will");
		tbr.add("            # break wood-like blocks in a radius. If you rightclick on shear-type blocks,");
		tbr.add("            # it will also break these blocks in a radius. The radius is dependent on the");
		tbr.add("            # charge level of the katar.");
		tbr.add("            BreakRadius: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.Katar.BreakRadius");
		tbr.add("");
		tbr.add("            # TillRadius: If you rightclick with a Katar on dirt or grass, it will till");
		tbr.add("            # all dirt and grass in a large radius around where the player clicked.");
		tbr.add("            # The radius is dependent on the charge level of the tool.");
		tbr.add("            #");
		tbr.add("            # Tip of Taeir: Disable this to prevent major \"nature grief\".");
		tbr.add("            TillRadius: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.Katar.TillRadius");
		tbr.add("");
		tbr.add("            # AttackRadius: If you press R with a Katar, you will attack mobs in a range");
		tbr.add("            # around you which is dependent on the charge level of the tool.");
		tbr.add("            # You can change the mode of the Katar to switch between only damaging");
		tbr.add("            # hostile mobs (excluding players) and all mobs (including players).");
		tbr.add("            AttackRadius: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.Katar.AttackRadius");
		tbr.add("");
		tbr.add("            # Shear: If you rightclick a shearable mob (sheep, mooshroom) with a Katar,");
		tbr.add("            # you will shear it.");
		tbr.add("            Shear: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.Katar.Shear");
		tbr.add("        MorningStar:");
		tbr.add("            # Break-3: See DM Pickaxe");
		tbr.add("            Break-3:");
		tbr.add("                Tall: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.MorningStar.Break-3.Tall");
		tbr.add("                Wide: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.MorningStar.Break-3.Wide");
		tbr.add("                Long: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.MorningStar.Break-3.Long");
		tbr.add("");
		tbr.add("            # MegaBreak: If you enable Mega Hammer mode, and you rightclick with a");
		tbr.add("            # Morning Star, it will break a very large cube of blocks around where you");
		tbr.add("            # clicked.");
		tbr.add("            MegaBreak: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.MorningStar.MegaBreak");
		tbr.add("");
		tbr.add("            # BreakRadius: Same effects as");
		tbr.add("            # - BreakOreVein for RM Pickaxe");
		tbr.add("            # - BreakRadius for RM Shovel");
		tbr.add("            # - BreakRadius for RM Hammer");
		tbr.add("            BreakRadius: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.MorningStar.BreakRadius");
		tbr.add("        Destruction:");
		tbr.add("            DestructionCatalyst:");
		tbr.add("                # BreakRadius: Break a large amount of blocks at once with the destruction");
		tbr.add("                # catalyst.");
		tbr.add("                BreakRadius: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.Destruction.DestructionCatalyst.BreakRadius");
		tbr.add("            HyperKineticLens:");
		tbr.add("                # BreakRadius: Break a large amount of blocks at once with the hyper");
		tbr.add("                # kinetic lens.");
		tbr.add("                BreakRadius: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.Destruction.HyperKineticLens.BreakRadius");
		tbr.add("            CatalyticLens:");
		tbr.add("                # BreakRadius: Break a large amount of blocks at once with the catalytic");
		tbr.add("                # lens.");
		tbr.add("                BreakRadius: true");
		if (extra) tbr.add("#:-;-:# Actions.Tools.Destruction.CatalyticLens.BreakRadius");
		tbr.add("    Amulets:");
		tbr.add("        Evertide:");
		tbr.add("            # CreateWater: Create a patch of water. The size depends on the chargelevel");
		tbr.add("            # of the Evertide Amulet.");
		tbr.add("            CreateWater: true");
		if (extra) tbr.add("#:-;-:# Actions.Amulets.Evertide.CreateWater");
		tbr.add("");
		tbr.add("            # CreateWaterBall: Shoot a WaterEssence that creates water where it hits.");
		tbr.add("            CreateWaterBall: true");
		if (extra) tbr.add("#:-;-:# Actions.Amulets.Evertide.CreateWaterBall");
		tbr.add("");
		tbr.add("            # PreventDrowing: Passive of the Evertide Amulet that prevents the player");
		tbr.add("            # from drowning.");
		tbr.add("            PreventDrowning: true");
		if (extra) tbr.add("#:-;-:# Actions.Amulets.Evertide.PreventDrowning");
		tbr.add("        Volcanite:");
		tbr.add("            # CreateLava: Create a patch of lava. The size depends on the chargelevel");
		tbr.add("            # of the Volcanite Amulet.");
		tbr.add("            CreateLava: true");
		if (extra) tbr.add("#:-;-:# Actions.Amulets.Volcanite.CreateLava");
		tbr.add("");
		tbr.add("            # CreateLavaBall: Shoot a LavaEssence that creates lava where it his.");
		tbr.add("            CreateLavaBall: true");
		if (extra) tbr.add("#:-;-:# Actions.Amulets.Volcanite.CreateLavaBall");
		tbr.add("");
		tbr.add("            # Vaporize: Vaporize water around the player.");
		tbr.add("            Vaporize: true");
		if (extra) tbr.add("#:-;-:# Actions.Amulets.Volcanite.Vaporize");
		tbr.add("");
		tbr.add("            # FireImmune: Passive of the Volcanite Amulet that prevents the player from");
		tbr.add("            # taking fire damage.");
		tbr.add("            FireImmune: true");
		if (extra) tbr.add("#:-;-:# Actions.Amulets.Volcanite.FireImmune");
		tbr.add("    Rings:");
		tbr.add("        ZeroRing:");
		tbr.add("            # FreezeRadius: When a Zero Ring is activated or if you rightclick with it, ");
		tbr.add("            # it will turn lava to obsidian, water to ice and put snow around the player.");
		tbr.add("            FreezeRadius: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.ZeroRing.FreezeRadius");
		tbr.add("");
		tbr.add("            # ThrowSnowball: If you leftclick with a Zero Ring, you throw a snowball.");
		tbr.add("            ThrowSnowball: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.ZeroRing.ThrowSnowball");
		tbr.add("");
		tbr.add("        RingOfIgnition:");
		tbr.add("            # BurnRadius: If you activate the Ring of Ignition it will cause things around");
		tbr.add("            # you to start burning (mobs, burnable blocks, etc.).");
		tbr.add("            #");
		tbr.add("            # If you rightclick with it or if you press R while holding it, it will make");
		tbr.add("            # large areas of fire.");
		tbr.add("            BurnRadius: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.RingOfIgnition.BurnRadius");
		tbr.add("");
		tbr.add("            # PassiveExtinguishNearPlayer: When you have the RingOfIgnition in your");
		tbr.add("            # hotbar, it will extinguish fires in a 3x3 block radius around the player.");
		tbr.add("            PassiveExtinguishNearPlayer: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.RingOfIgnition.PassiveExtinguishNearPlayer");
		tbr.add("");
		tbr.add("            # ThrowPyrokinesis: If you leftclick with a Ring of Ignition, you will create");
		tbr.add("            # a fireball that spawns fire where it hits.");
		tbr.add("            ThrowPyrokinesis: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.RingOfIgnition.ThrowPyrokinesis");
		tbr.add("");
		tbr.add("        HarvestGodessBand:");
		tbr.add("            # Fertilize: If you have a Harvest Godess Band in your hotbar, it will cause");
		tbr.add("            # plants around you to grow faster and it will turn dirt around you to grass.");
		tbr.add("            # If you activate it, it will also plant plants around you.");
		tbr.add("            Fertilize: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.HarvestGodessBand.Fertilize");
		tbr.add("");
		tbr.add("            # PlantRadius: If you rightclick with a Harvest Godess Band, it will take seeds,");
		tbr.add("            # reeds, cacti, flowers and other plants from your inventory and plant them");
		tbr.add("            # near you.");
		tbr.add("            PlantRadius: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.HarvestGodessBand.PlantRadius");
		tbr.add("");
		tbr.add("            # HarvestRadius: If you activate a Harvest Godess Band, it will harvest mature");
		tbr.add("            # plants around you. It also increases the speed at which plants around you");
		tbr.add("            # mature.");
		tbr.add("            HarvestRadius: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.HarvestGodessBand.HarvestRadius");
		tbr.add("");
		tbr.add("        SwiftwolfsRendingGale:");
		tbr.add("            # NOTE: SWRG is short for Swiftwolf's Rending Gale");
		tbr.add("");
		tbr.add("            # NegateFallDamage: The SWRG will negate all fall damage if it's in the hotbar");
		tbr.add("            # (Passive)");
		tbr.add("            NegateFallDamage: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.SwiftwolfsRendingGale.NegateFallDamage");
		tbr.add("");
		tbr.add("            # Interdict: When you press the G key while holding the SWRG, you will activate");
		tbr.add("            # interdiction mode. While it is active, all mobs that try to come close to you");
		tbr.add("            # will be pushed back.");
		tbr.add("            Interdict: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.SwiftwolfsRendingGale.Interdict");
		tbr.add("");
		tbr.add("            # Gust: If you rightclick with a SWRG or if you press R while holding it, it");
		tbr.add("            # will create a gust. If the gust hits a block or the sky while it is raining,");
		tbr.add("            # it will let lightning strike at the location where it hit.");
		tbr.add("            # (random location if shot into the sky).");
		tbr.add("            Gust: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.SwiftwolfsRendingGale.Gust");
		tbr.add("");
		tbr.add("            # ActivateInterdict: Defines whether the player can activate interdiction mode.");
		tbr.add("            ActivateInterdict: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.SwiftwolfsRendingGale.ActivateInterdict");
		tbr.add("");
		tbr.add("            # ActivateFlight: Defines whether the player can activate flight mode.");
		tbr.add("            ActivateFlight: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.SwiftwolfsRendingGale.ActivateFlight");
		tbr.add("");
		tbr.add("        RingOfArcana:");
		tbr.add("            # StrikeLightning: If you press R while holding a Ring of Arcana in \"Wind\" mode");
		tbr.add("            # it will make lightning strike on hostile mobs near you.");
		tbr.add("            StrikeLightning: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.RingOfArcana.StrikeLightning");
		tbr.add("");
		tbr.add("            # Fertilize: If you have a Ring of Arcana in \"Earth\" mode in your hotbar,");
		tbr.add("            # it will make plants around you mature faster. It will also plant new plants");
		tbr.add("            # in your vicinity. (Passive)");
		tbr.add("            #");
		tbr.add("            # If you press R while holding it in \"Earth\" mode, it will take seeds, reeds,");
		tbr.add("            # cacti, flowers and other plants from your inventory and plant them around");
		tbr.add("            # you.");
		tbr.add("            # It will also use bonemeal (if you have any) to let saplings grow into trees");
		tbr.add("            # and to make wheat mature instantly.");
		tbr.add("            Fertilize: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.RingOfArcana.Fertilize");
		tbr.add("");
		tbr.add("            # Interdict: When you activate the Ring of Arcana in \"Wind\" mode, you will");
		tbr.add("            # activate interdiction mode. While it is active, all mobs that try to come");
		tbr.add("            # close to you will be pushed back.");
		tbr.add("            Interdict: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.RingOfArcana.Interdict");
		tbr.add("");
		tbr.add("            # FreezeRadius: When you activate the Ring of Arcana in in \"Ice\" mode, it will");
		tbr.add("            # turn lava to obsidian, water to ice and put snow around the player.");
		tbr.add("            #");
		tbr.add("            # If you press R while holding it in \"Ice\" mode, it will do this effect in a");
		tbr.add("            # square around you instantly.");
		tbr.add("            FreezeRadius: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.RingOfArcana.FreezeRadius");
		tbr.add("");
		tbr.add("            # BurnRadius: If you activate the Ring of Arcana in \"Fire\" mode, it will cause");
		tbr.add("            # things around you to start burning (mobs, burnable blocks, etc.).");
		tbr.add("            #");
		tbr.add("            # If you press R while holding it in \"Fire\" mode, it will make a large area of");
		tbr.add("            # fire around you.");
		tbr.add("            BurnRadius: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.RingOfArcana.BurnRadius");
		tbr.add("");
		tbr.add("            # HarvestRadius: If you activate the Ring of Arcana in \"Earth\" mode, it will");
		tbr.add("            # harvest matured plants around you. It will also make plants around you to");
		tbr.add("            # grow faster.");
		tbr.add("            HarvestRadius: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.RingOfArcana.HarvestRadius");
		tbr.add("");
		tbr.add("            # Gust: If you rightclick with a Ring of Arcana in \"Wind\" mode, it will create");
		tbr.add("            # a gust. If the gust hits a block or the sky while it is raining, it will let");
		tbr.add("            # lightning strike at the location where it hit.");
		tbr.add("            # (random location if shot into the sky).");
		tbr.add("            Gust: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.RingOfArcana.Gust");
		tbr.add("");
		tbr.add("            # ThrowSnowball: If you rightclick with a Ring of Arana in \"Ice\" mode, it will");
		tbr.add("            # throw a snowball.");
		tbr.add("            ThrowSnowball: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.RingOfArcana.ThrowSnowball");
		tbr.add("");
		tbr.add("            # ThrowPyrokinesis: If you rightclick with a Ring of Arana in \"Fire\" mode, it");
		tbr.add("            # will throw a fireball that creates fire where it hits.");
		tbr.add("            ThrowPyrokinesis: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.RingOfArcana.ThrowPyrokinesis");
		tbr.add("");
		tbr.add("            # NegateFallDamage: The Ring of Arcana will negate all fall damage if it is in");
		tbr.add("            # the hotbar. (Passive)");
		tbr.add("            NegateFallDamage: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.RingOfArcana.NegateFallDamage");
		tbr.add("");
		tbr.add("            # Activate: Defines whether a player can activate the ring or not.");
		tbr.add("            Activate: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.RingOfArcana.Activate");
		tbr.add("");
		tbr.add("        BlackHoleBand:");
		tbr.add("            # NOTE: BHB is short for Black Hole Band");
		tbr.add("");
		tbr.add("            # AttractItems: If you activate a BHB, it will start to attract items within");
		tbr.add("            # a 7 block radius to you.");
		tbr.add("            AttractItems: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.BlackHoleBand.AttractItems");
		tbr.add("");
		tbr.add("            # DeleteLiquid: If you rightclick with a BHB on a water or lava source block,");
		tbr.add("            # it will remove it.");
		tbr.add("            DeleteLiquid: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.BlackHoleBand.DeleteLiquid");
		tbr.add("");
		tbr.add("            # Activate: Defines whether a player can activate the BHB or not.");
		tbr.add("            Activate: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.BlackHoleBand.Activate");
		tbr.add("");
		tbr.add("        VoidRing:");
		tbr.add("            # AttractItems: If you activate a Void Ring, it will start to attract items");
		tbr.add("            # within a 7 block radius to you.");
		tbr.add("            AttractItems: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.VoidRing.AttractItems");
		tbr.add("");
		tbr.add("            # DeleteLiquid: If you rightclick with a Void Ring on a water or lava source");
		tbr.add("            # block, it will remove it.");
		tbr.add("            DeleteLiquid: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.VoidRing.DeleteLiquid");
		tbr.add("");
		tbr.add("            # Teleport: If you press R while holding a Void Ring, it will teleport you");
		tbr.add("            # to a new location depending on the direction you are facing. It can teleport");
		tbr.add("            # through walls.");
		tbr.add("            Teleport: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.VoidRing.Teleport");
		tbr.add("");
		tbr.add("            # Condense: If you have an activated Void Ring in your inventory, it will");
		tbr.add("            # condense all items with an emc value that are not tools into compacter forms");
		tbr.add("            # (Iron Ingots, Gold Ingots, Diamonds, Dark Matter or Red Matter).");
		tbr.add("            Condense: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.VoidRing.Condense");
		tbr.add("");
		tbr.add("            # Activate: Defines whether a player can activate the Void Ring or not.");
		tbr.add("            Activate: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.VoidRing.Activate");
		tbr.add("");
		tbr.add("        ArchangelsSmite:");
		tbr.add("            # ShootArrows: If you activate the ArchangelsSmite, it will constantly shoot");
		tbr.add("            # homing arrows (while using EMC).");
		tbr.add("            ShootArrows: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.ArchangelsSmite.ShootArrows");
		tbr.add("");
		tbr.add("            # Activate: Defines whether a player can activate the ArchangelsSmite or not.");
		tbr.add("            Activate: true");
		if (extra) tbr.add("#:-;-:# Actions.Rings.ArchangelsSmite.Activate");
		tbr.add("    Armor:");
		tbr.add("        Offensive:");
		tbr.add("            # Activate: Defines whether a player can activate offensive powers or not.");
		tbr.add("            Activate: true");
		if (extra) tbr.add("#:-;-:# Actions.Armor.Offensive.Activate");
		tbr.add("");
		tbr.add("            # Explode: If you press the C key while wearing Gem armor, an explosion");
		tbr.add("            # will be created around a player.");
		tbr.add("            Explode: true");
		if (extra) tbr.add("#:-;-:# Actions.Armor.Offensive.Explode");
		tbr.add("");
		tbr.add("            # Strike: If you press the R key while wearing a Gem armor Helmet, a");
		tbr.add("            # lightning bolt will hit where you look.");
		tbr.add("            Strike: true");
		if (extra) tbr.add("#:-;-:# Actions.Armor.Offensive.Strike");
		tbr.add("        Movement:");
		tbr.add("            # Activate: Defines whether a player can activate movement powers or not.");
		tbr.add("            Activate: true");
		if (extra) tbr.add("#:-;-:# Actions.Armor.Movement.Activate");
		tbr.add("    Other:");
		tbr.add("        PhilosopherStone:");
		tbr.add("            # ChangeMob: The ability to change a mob into a different one at the cost");
		tbr.add("            # of emc.");
		tbr.add("            ChangeMob: true");
		if (extra) tbr.add("#:-;-:# Actions.Other.PhilosopherStone.ChangeMob");
		tbr.add("");
		tbr.add("            # PortableCrafting: The ability to open a crafting table by pressing C");
		tbr.add("            # while holding the Philosopher's Stone.");
		tbr.add("            PortableCrafting: true");
		if (extra) tbr.add("#:-;-:# Actions.Other.PhilosopherStone.PortableCrafting");
		tbr.add("");
		tbr.add("            # Transmute: The ability to change a block into a different one by");
		tbr.add("            # right-clicking on it with the Philosopher's Stone.");
		tbr.add("            Transmute: true");
		if (extra) tbr.add("#:-;-:# Actions.Other.PhilosopherStone.Transmute");
		tbr.add("        TransmutionTablet:");
		tbr.add("            # ChangeMob: The ability to change a mob into a different one at the cost");
		tbr.add("            # of emc.");
		tbr.add("            ChangeMob: true");
		if (extra) tbr.add("#:-;-:# Actions.Other.TransmutionTablet.ChangeMob");
		tbr.add("");
		tbr.add("            # PortableTable: The ability to open your Transmution Table by pressing C");
		tbr.add("            # or right-clicking with the Transution Tablet.");
		tbr.add("            PortableTable: true");
		if (extra) tbr.add("#:-;-:# Actions.Other.TransmutionTablet.PortableTable");
		tbr.add("        Pedestal:");
		tbr.add("            # Activate: If players should be able to activate pedestals.");
		tbr.add("            Activate: true");
		if (extra) tbr.add("#:-;-:# Actions.Other.Pedestal.Activate");
		tbr.add("");
		tbr.add("            # Attract: If pedestals are allowed to attract items if the Black Hole Band");
		tbr.add("            # is on them.");
		tbr.add("            Attract: true");
		if (extra) tbr.add("#:-;-:# Actions.Other.Pedestal.Attract");
		tbr.add("");
		tbr.add("            # Harvest: If pedestals are allowed to harvest nearby crops if the Harvest");
		tbr.add("            # Godess Band is on them.");
		tbr.add("            Harvest: true");
		if (extra) tbr.add("#:-;-:# Actions.Other.Pedestal.Harvest");
		tbr.add("");
		tbr.add("            # Heal: If pedestals are allowed to heal nearby players if the Life Stone");
		tbr.add("            # is on them.");
		tbr.add("            Heal: true");
		if (extra) tbr.add("#:-;-:# Actions.Other.Pedestal.Heal");
		tbr.add("");
		tbr.add("            # Ignition: If pedestals are allowed to ignite nearby entities if the");
		tbr.add("            # Ring of Ignition is on them.");
		tbr.add("            Ignition: true");
		if (extra) tbr.add("#:-;-:# Actions.Other.Pedestal.Ignition");
		tbr.add("");
		tbr.add("            # Interdict: If pedestals are allowed to push mobs away from them.");
		tbr.add("            Interdict: true");
		if (extra) tbr.add("#:-;-:# Actions.Other.Pedestal.Interdict");
		tbr.add("");
		tbr.add("            # Repair: If pedestals are allowed to repair items in the inventories of");
		tbr.add("            # nearby players if the Repair Talisman is on them.");
		tbr.add("            Repair: true");
		if (extra) tbr.add("#:-;-:# Actions.Other.Pedestal.Repair");
		tbr.add("");
		tbr.add("            # ShootArrow: If pedestals are allowed to shoot arrows at nearby entities");
		tbr.add("            # if the Grimarch Ring is on them.");
		tbr.add("            ShootArrow: true");
		if (extra) tbr.add("#:-;-:# Actions.Other.Pedestal.ShootArrow");
		tbr.add("");
		tbr.add("            # StopStorm: If pedestals are allowed to stop storms from occuring when");
		tbr.add("            # ???? is on them.");
		tbr.add("            StopStorm: true");
		if (extra) tbr.add("#:-;-:# Actions.Other.Pedestal.StopStorm");
		tbr.add("");
		tbr.add("            # Storm: If pedestals are allowed to start storms if ???? is on them.");
		tbr.add("            Storm: true");
		if (extra) tbr.add("#:-;-:# Actions.Other.Pedestal.Storm");
		tbr.add("");
		tbr.add("            # StrikeLightning: If pedestals are allowed to strike lightning at nearby");
		tbr.add("            # entities if ???? is on them.");
		tbr.add("            StrikeLightning: true");
		if (extra) tbr.add("#:-;-:# Actions.Other.Pedestal.StrikeLightning");
		tbr.add("");
		tbr.add("            # Time: If pedestals are allowed to speed up EE machines when the Watch of");
		tbr.add("            # Flowing Time is on them.");
		tbr.add("            Time: true");
		if (extra) tbr.add("#:-;-:# Actions.Other.Pedestal.Time");
		tbr.add("        WatchOfFlowingTime:");
		tbr.add("            # ScrollTimeForwards: The ability to make time go faster with the watch.");
		tbr.add("            ScrollTimeForwards: true");
		if (extra) tbr.add("#:-;-:# Actions.Other.WatchOfFlowingTime.ScrollTimeForwards");
		tbr.add("");
		tbr.add("            # ScrollTimeBackwards: The ability to make time go backwards with the watch.");
		tbr.add("            ScrollTimeBackwards: true");
		if (extra) tbr.add("#:-;-:# Actions.Other.WatchOfFlowingTime.ScrollTimeBackwards");
		tbr.add("");
		tbr.add("#########################################################################################");
		tbr.add("# By default, the RM furnace doubles the amount of ingots you get from smelting");
		tbr.add("# ores. If you set AllowRMFurnaceOreDuplication: false, you will always get one ingot");
		tbr.add("# when you smelt one ore.");
		tbr.add("#");
		tbr.add("# Default: true");
		tbr.add("AllowRMFurnaceOreDuplication: true");
		if (extra) tbr.add("#:-;-:# AllowRMFurnaceOreDuplication");//1
		tbr.add("");
		tbr.add("#########################################################################################");
		
		return tbr;
	}
	
	public static void upgradeFile(){
		upgradeFile("EEPatch", convertDefaults(defaultContents(true)));
	}
}