package nl.taico.tekkitrestrict.config;

import java.util.ArrayList;

public class SafeZonesConfig extends TRConfig {
	public static ArrayList<String> defaultContents(boolean extra){
		ArrayList<String> tbr = new ArrayList<String>();
		
		tbr.add("##########################################################################################");
		tbr.add("## Configuration file for TekkitRestrict                                                ##");
		tbr.add("## Authors: Taeir, DreadEnd (aka DreadSlicer)                                           ##");
		tbr.add("## BukkitDev: http://dev.bukkit.org/server-mods/tekkit-restrict/                        ##");
		tbr.add("## Please ask questions/report issues on the BukkitDev page.                            ##");
		tbr.add("##########################################################################################");
		tbr.add("");
		tbr.add("##########################################################################################");
		tbr.add("################################# SafeZone Configuration #################################");
		tbr.add("##########################################################################################");
		tbr.add("");
		tbr.add("# Should TekkitRestrict use SafeZones?");
		tbr.add("# Default: true");
		tbr.add("UseSafeZones: true");
		if (extra) tbr.add("#:-;-:# UseSafeZones");
		tbr.add("");
		tbr.add("# Note: This will only apply to WorldGuard and GriefPrevention SafeZones, and");
		tbr.add("#       NOT to Towny, Factions or PreciousStones SafeZones.");
		tbr.add("InSafeZones:");
		tbr.add("    # If you turn DisableEntities on, then");
		tbr.add("    # - No mobs will spawn in SafeZones.");
		tbr.add("    # - If a mob enters a SafeZone, it is removed.");
		tbr.add("    # Default: true");
		tbr.add("    DisableEntities: true");
		if (extra) tbr.add("#:-;-:# InSafeZones.DisableEntities");
		tbr.add("    ");
		tbr.add("    # WARNING: Case Sensitive!");
		tbr.add("    # Tries to exclude org.bukkit.entity.[name] entities from SafeZone entity removal.");
		tbr.add("    # Examples:");
		tbr.add("    # \"Arrow\", \"Animals\", \"EnderDragon\", \"EnderPearl\", \"Fish\", \"IronGolem\", \"Pig\",");
		tbr.add("    # \"Projectile\", \"ThrownPotion\", \"TNTPrimed\", \"Snowball\"");
		tbr.add("    ExemptEntityTypes: []");
		if (extra) tbr.add("#:-;-:# InSafeZones.ExemptEntityTypes");
		tbr.add("");
		tbr.add("    # If you turn DechargeEE on, then");
		tbr.add("    # - All EE items specified in the ModModifications config will be decharged");
		tbr.add("    #   in SafeZones");
		tbr.add("    # Default: true");
		tbr.add("    DechargeEE: true");
		if (extra) tbr.add("#:-;-:# InSafeZones.DechargeEE");
		tbr.add("");
		tbr.add("    # If you turn DisableRingOfArcana on, then");
		tbr.add("    # - When someone is in a SafeZone with a ring of arcana, it will always be set");
		tbr.add("    #   to \"Earth\" mode and it will be turned off.");
		tbr.add("    # Default: true");
		tbr.add("    DisableRingOfArcana: true");
		if (extra) tbr.add("#:-;-:# InSafeZones.DisableRingOfArcana");
		tbr.add("");
		tbr.add("    # If you turn DisableFlying on, then");
		tbr.add("    # - All flying items will be disabled when you are in a SafeZone.");
		tbr.add("    # DisableFlying: false");
		tbr.add("    # This feature does not work (yet).");
		tbr.add("");
		tbr.add("# The plugins TekkitRestrict should use to make safezones.");
		tbr.add("#");
		tbr.add("# There is only basic support for Factions, Towny and PreciousStones.");
		tbr.add("# This means that all land claimed by a faction, a town, etcetera is a safezone.");
		tbr.add("# Players with the build/destroy permission for that land will bypass it.");
		tbr.add("#");
		tbr.add("# For GriefPrevention, you can choose different modes (See below).");
		tbr.add("# For WorldGuard, you can specify per region if it should be a safezone. You can");
		tbr.add("# compare this mode with the \"Specific\" mode of GriefPrevention.");
		tbr.add("# Default: true for all");
		tbr.add("SSEnabledPlugins: ");
		tbr.add("    GriefPrevention: true");
		if (extra) tbr.add("#:-;-:# SSEnabledPlugins.GriefPrevention");
		tbr.add("    WorldGuard: true");
		if (extra) tbr.add("#:-;-:# SSEnabledPlugins.WorldGuard");
		tbr.add("    Factions: true");
		if (extra) tbr.add("#:-;-:# SSEnabledPlugins.Factions");
		tbr.add("    Towny: true");
		if (extra) tbr.add("#:-;-:# SSEnabledPlugins.Towny");
		tbr.add("    PreciousStones: true");
		if (extra) tbr.add("#:-;-:# SSEnabledPlugins.PreciousStones");
		tbr.add("");
		tbr.add("##########################################################################################");
		tbr.add("############################ GriefPrevention Specific settings ###########################");
		tbr.add("##########################################################################################");
		tbr.add("");
		tbr.add("# If someone is a manager in a claim, the SafeZone will not apply for him.");
		tbr.add("# (If you would like a setting to turn this on or off, please make a feature request");
		tbr.add("# ticket on the Bukkit Dev TekkitRestrict page.)");
		tbr.add("");
		tbr.add("# GriefPrevention SafeZone Method");
		tbr.add("# Can be \"All\", \"Admin\", \"Specific\" or \"SpecificAdmin\"");
		tbr.add("# \"All\": All GriefPrevention claims are SafeZones.");
		tbr.add("# \"Admin\": All GriefPrevention admin claims are SafeZones. (Default)");
		tbr.add("# \"Specific\": You can specify per claim if you want it to be a SafeZone.");
		tbr.add("# \"SpecificAdmin\": Only admin claims can be SafeZones, but you can specify it per claim.");
		tbr.add("GriefPreventionSafeZoneMethod: \"Admin\"");
		if (extra) tbr.add("#:-;-:# GriefPreventionSafeZoneMethod");
		tbr.add("");
		tbr.add("##########################################################################################");
		tbr.add("############################## WorldGuard Specific settings ##############################");
		tbr.add("##########################################################################################");
		tbr.add("");
		tbr.add("# WorldGuard SafeZone Method");
		tbr.add("# Can be \"All\" or \"Specific\"");
		tbr.add("# \"All\": All WorldGuard regions are SafeZones.");
		tbr.add("# \"Specific\": You can specify per region if you want it to be a SafeZone. (Default)");
		tbr.add("WorldGuardSafeZoneMethod: \"Specific\"");
		if (extra) tbr.add("#:-;-:# WorldGuardSafeZoneMethod");
		tbr.add("");
		tbr.add("##########################################################################################");
		
		return tbr;
	}
	
	public static void upgradeFile(){
		upgradeFile("SafeZones", convertDefaultsShortList(defaultContents(true)));
	}
}
